const $=id=>document.getElementById(id), canvas=$('canvas'),ctx=canvas.getContext('2d');
const definitions=[['생명선','엄지 둘레를 감싸는 곡선','#61dec9'],['두뇌선','손바닥 중앙을 가로지르는 선','#69aaff'],['감정선','손가락 바로 아래를 가로지르는 선','#f9a0bd'],['운명선','손목에서 중지 방향으로 올라가는 세로선','#f2c66e']];
let image=null,active=0,paths=[[],[],[],[]],drawing=false,url=null,rotation=0;
function buttons(){ $('lines').replaceChildren();definitions.forEach((d,i)=>{const b=document.createElement('button');b.className='line'+(i===active?' active':'');b.style.setProperty('--color',d[2]);b.innerHTML=`<span class="dot"></span><span><strong>${d[0]}</strong><span class="desc">${d[1]}</span></span><em>${paths[i].length>1?'그림 완료':'미입력'}</em>`;b.onclick=()=>{active=i;buttons()};$('lines').append(b)});$('analyze').disabled=!paths.some(p=>p.length>1);$('undo').disabled=!image;$('clear').disabled=!image;$('rotate').disabled=!image;}
function render(){if(!image)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(rotation*Math.PI/180);const swapped=rotation%180!==0;ctx.drawImage(image,-(swapped?canvas.height:canvas.width)/2,-(swapped?canvas.width:canvas.height)/2,swapped?canvas.height:canvas.width,swapped?canvas.width:canvas.height);ctx.restore();paths.forEach((p,i)=>{if(p.length<2)return;ctx.beginPath();p.forEach((v,j)=>j?ctx.lineTo(v.x*canvas.width,v.y*canvas.height):ctx.moveTo(v.x*canvas.width,v.y*canvas.height));ctx.strokeStyle=definitions[i][2];ctx.lineWidth=Math.max(4,canvas.width/160);ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke()})}
function point(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
canvas.onpointerdown=e=>{if(!image)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);drawing=true;paths[active]=[point(e)];$('result').hidden=true;render()};canvas.onpointermove=e=>{if(!drawing)return;const p=point(e),last=paths[active].at(-1);if(Math.hypot(p.x-last.x,p.y-last.y)>.003){paths[active].push(p);render()}};function finish(){if(!drawing)return;drawing=false;if(paths[active].length<3)paths[active]=[];buttons();render();$('status').textContent=definitions[active][0]+' 입력 완료. 다음 선을 선택해 주세요.'}canvas.onpointerup=finish;canvas.onpointercancel=finish;
$('file').onchange=()=>{const file=$('file').files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024){$('status').textContent='15MB 이하의 JPG, PNG, WebP 사진을 선택해 주세요.';return}const next=URL.createObjectURL(file),im=new Image();im.onload=()=>{if(url)URL.revokeObjectURL(url);url=next;image=im;rotation=0;paths=[[],[],[],[]];active=0;const scale=Math.min(1,1200/Math.max(im.width,im.height));canvas.width=Math.round(im.width*scale);canvas.height=Math.round(im.height*scale);canvas.hidden=false;$('empty').hidden=true;$('result').hidden=true;render();buttons();$('status').textContent='사진 준비 완료. 선을 선택하고 손가락으로 따라 그려 주세요.'};im.onerror=()=>{URL.revokeObjectURL(next);$('status').textContent='사진을 열지 못했습니다. 다른 사진을 선택해 주세요.'};im.src=next};
$('rotate').onclick=()=>{rotation=(rotation+90)%360;[canvas.width,canvas.height]=[canvas.height,canvas.width];paths=[[],[],[],[]];$('result').hidden=true;render();buttons();$('status').textContent='사진을 회전했습니다. 손금을 다시 그려 주세요.'};$('undo').onclick=()=>{paths[active]=[];$('result').hidden=true;render();buttons()};$('clear').onclick=()=>{paths=[[],[],[],[]];$('result').hidden=true;render();buttons()};$('hand').onchange=()=>{$('result').hidden=true};
function measure(p){let length=0;for(let i=1;i<p.length;i++)length+=Math.hypot((p[i].x-p[i-1].x)*canvas.width,(p[i].y-p[i-1].y)*canvas.height);const direct=Math.hypot((p.at(-1).x-p[0].x)*canvas.width,(p.at(-1).y-p[0].y)*canvas.height);return{length:length/Math.hypot(canvas.width,canvas.height),curve:length/Math.max(direct,1)}}
const meanings=[['활동·생활의 상징','전통적으로 생명선은 생활의 활력과 활동 범위를 상징합니다. 크게 굽은 형태는 활동적인 이미지, 비교적 곧은 형태는 일정한 생활 리듬의 이미지로 풀이합니다. 선의 길이는 수명이나 건강을 뜻하지 않습니다.'],['사고방식·직업의 상징','전통적으로 비교적 곧은 두뇌선은 실용적 사고, 굽은 두뇌선은 상상력의 상징으로 풀이합니다. 직업 이야기에서는 각각 계획·실무와 창작·아이디어에 연결하지만 실제 능력이나 적합성을 확인할 수는 없습니다.'],['감정·관계의 상징','전통적으로 길게 이어지는 감정선은 관계를 중시하는 이미지, 짧게 그려진 선은 감정을 간결하게 표현하는 이미지로 풀이합니다. 상대방과의 궁합이나 결혼 시기를 알려주는 근거는 아닙니다.'],['직업·사업·재물의 상징','전통적으로 운명선은 사회적 활동과 삶의 방향을 상징합니다. 길게 이어진 선은 꾸준한 활동의 이미지로 이야기합니다. 선이 짧거나 보이지 않아도 직업운이나 재물운이 나쁘다는 뜻은 아닙니다. 사업 성공과 재산 규모는 판단할 수 없습니다.']];
$('analyze').onclick=()=>{const reports=[];$('cards').replaceChildren();definitions.forEach((d,i)=>{const card=document.createElement('article');card.className='card';const title=document.createElement('h3');title.textContent=d[0]+' · '+meanings[i][0];card.append(title);if(paths[i].length<2){const p=document.createElement('p');p.textContent='선이 입력되지 않아 해석을 생략했습니다.';card.append(p);reports.push(d[0]+': 미입력')}else{const m=measure(paths[i]);const description=`그린 길이: 사진 대각선 대비 ${Math.round(m.length*100)}% · 형태: ${m.curve>1.15?'굽음이 있는 선':'비교적 곧은 선'}`;const metric=document.createElement('div');metric.className='metric';metric.textContent=description;const p=document.createElement('p');p.textContent=meanings[i][1];card.append(metric,p);reports.push(d[0]+'\n'+description+'\n'+meanings[i][1])}$('cards').append(card)});const summary=$('hand').value+' · 직접 그린 선 '+paths.filter(p=>p.length>1).length+'개를 바탕으로 한 전통적 해석입니다. 측정값은 사진의 여백과 그리는 방식에 따라 달라집니다.';$('summary').textContent=summary;$('copytext').value='손금 노트 — 재미용 전통 해석\n'+summary+'\n\n'+reports.join('\n\n')+'\n\n사진으로 건강·수명, 투자 성과, 미래의 사건이나 연령별 운세를 예측할 수 없습니다.';$('result').hidden=false;$('result').scrollIntoView({behavior:'smooth',block:'start'})};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('copytext').value);$('copy').textContent='복사 완료'}catch{$('copytext').focus();$('copytext').select();$('copy').textContent='아래 결과를 길게 눌러 복사'}setTimeout(()=>$('copy').textContent='전체 결과 복사',2500)};buttons();
