// Local contrast ridge tracking. Candidate labels rely on an upright, centered palm.
const hands={왼손:null,오른손:null};let currentHand=$('hand').value;
function saveHand(){if(image)hands[currentHand]={image,url,rotation,paths:paths.map(p=>p.map(v=>({...v}))),width:canvas.width,height:canvas.height}}
function showHand(name){saveHand();currentHand=name;$('hand').value=name;const h=hands[name];image=h?.image||null;url=h?.url||null;rotation=h?.rotation||0;paths=h?.paths.map(p=>p.map(v=>({...v})))||[[],[],[],[]];if(h){canvas.width=h.width;canvas.height=h.height;render()}canvas.hidden=!h;$('empty').hidden=!!h;buttons();$('result').hidden=true}
$('hand').onchange=()=>showHand($('hand').value);
function pairStatus(){ $('pair-status').textContent=Object.keys(hands).map(k=>k+' '+(hands[k]?'사진 준비됨':'미입력')).join(' · ');$('auto').disabled=!Object.values(hands).some(Boolean)}
async function loadHand(name,file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024){$('status').textContent='15MB 이하 JPG·PNG·WebP를 선택하세요.';return}const next=URL.createObjectURL(file),im=new Image();try{im.src=next;await im.decode();saveHand();if(hands[name]?.url)URL.revokeObjectURL(hands[name].url);const scale=Math.min(1,1200/Math.max(im.width,im.height));hands[name]={image:im,url:next,rotation:0,paths:[[],[],[],[]],width:Math.round(im.width*scale),height:Math.round(im.height*scale)};image=null;showHand(name);pairStatus();$('status').textContent=name+' 준비 완료. 양손 사진을 선택한 뒤 자동 찾기를 누르세요.'}catch{URL.revokeObjectURL(next);$('status').textContent='사진을 열지 못했습니다.'}}
$('left-file').onchange=()=>loadHand('왼손',$('left-file').files[0]);$('right-file').onchange=()=>loadHand('오른손',$('right-file').files[0]);
function ridgeCandidates(rgba,w,h,hand){const gray=new Float32Array(w*h),ridge=new Float32Array(w*h);for(let i=0;i<gray.length;i++)gray[i]=rgba[i*4]*.299+rgba[i*4+1]*.587+rgba[i*4+2]*.114;for(let y=5;y<h-5;y++)for(let x=5;x<w-5;x++){const i=y*w+x;const contrast=Math.max((gray[i-4]+gray[i+4])/2-gray[i],(gray[i-4*w]+gray[i+4*w])/2-gray[i]);ridge[i]=gray[i]>35&&gray[i]<245?Math.max(0,contrast):0}
// Dynamic paths follow measured contrast, never return a default geometric line.
function track(vertical,lo,hi,start,end){const n=vertical?h:w,m=vertical?w:h,a=Math.floor(n*start),b=Math.floor(n*end),l=Math.floor(m*lo),r=Math.floor(m*hi),span=r-l+1;let prev=new Float32Array(span);const back=[];for(let t=a;t<=b;t++){const next=new Float32Array(span),parents=new Int16Array(span);for(let j=0;j<span;j++){let best=-Infinity,kbest=j;for(let k=Math.max(0,j-2);k<=Math.min(span-1,j+2);k++){const v=prev[k]-Math.abs(j-k)*1.8;if(v>best){best=v;kbest=k}}const x=vertical?l+j:t,y=vertical?t:l+j;next[j]=best+Math.min(25,ridge[y*w+x]);parents[j]=kbest}back.push(parents);prev=next}let j=prev.indexOf(Math.max(...prev)),p=[];for(let t=b;t>=a;t--){p.push({x:(vertical?l+j:t)/w,y:(vertical?t:l+j)/h});j=back[t-a][j]}p.reverse();const strengths=p.map(v=>ridge[Math.min(h-1,Math.floor(v.y*h))*w+Math.min(w-1,Math.floor(v.x*w))]);const supported=strengths.filter(v=>v>5).length/p.length;if(supported<.35||strengths.reduce((a,b)=>a+b,0)/p.length<5)return [];return p.filter((_,i)=>i%3===0||i===p.length-1)}
return [track(true,hand==='왼손'?.42:.22,hand==='왼손'?.78:.58,.42,.82),track(false,.47,.67,.23,.77),track(false,.30,.47,.23,.77),track(true,.42,.62,.55,.86)]}
async function detectCurrent(){paths=[[],[],[],[]];render();const small=document.createElement('canvas');small.width=240;small.height=Math.max(120,Math.round(240*canvas.height/canvas.width));const c=small.getContext('2d');c.drawImage(canvas,0,0,small.width,small.height);paths=ridgeCandidates(c.getImageData(0,0,small.width,small.height).data,small.width,small.height,currentHand);render();buttons();saveHand()}
const oldAnalyze=$('analyze').onclick;
$('analyze').onclick=()=>{saveHand();oldAnalyze();const cards=$('cards');cards.replaceChildren();let lines=[];for(const [name,h] of Object.entries(hands)){if(!h)continue;const title=document.createElement('h3');title.textContent=name+' · 주요 손금 후보';cards.append(title);lines.push(name);h.paths.forEach((p,i)=>{const a=document.createElement('article');a.className='card';const heading=document.createElement('h3');heading.textContent=definitions[i][0];const detail=document.createElement('p');let text='뚜렷한 후보를 찾지 못했습니다. 사진에서 확인하거나 직접 그려 주세요.';if(p.length>1){let len=0;for(let k=1;k<p.length;k++)len+=Math.hypot((p[k].x-p[k-1].x)*h.width,(p[k].y-p[k-1].y)*h.height);const direct=Math.hypot((p.at(-1).x-p[0].x)*h.width,(p.at(-1).y-p[0].y)*h.height);const curved=len/Math.max(1,direct)>1.15;const readings=['활동 범위와 생활 리듬의 상징',curved?'상상력과 아이디어의 상징':'실용적 사고와 계획의 상징','관계와 감정 표현의 상징','사회 활동과 삶의 방향의 상징'];text='길이 '+Math.round(len/Math.hypot(h.width,h.height)*100)+'% · '+(curved?'굽음이 있는 선':'비교적 곧은 선')+'\n전통적 의미: '+readings[i]+'.';}detail.textContent=text;a.append(heading,detail);cards.append(a);lines.push(definitions[i][0]+': '+text)})}$('summary').textContent='양손의 주름 후보를 비교하는 재미용 해석입니다. 후보의 이름은 사진 구도에 따른 추정이며, 실제 손금과 일치하는지 확인하세요.';$('copytext').value='손금 노트 · 양손 요약\n'+lines.join('\n\n')+'\n\n건강·수명·성격·미래를 예측하는 과학적 분석이 아닙니다.'};
$('auto').onclick=async()=>{const b=$('auto');b.disabled=true;$('status').textContent='사진의 주름 후보를 찾고 있습니다…';try{saveHand();for(const name of Object.keys(hands)){if(!hands[name])continue;showHand(name);await new Promise(r=>setTimeout(r,20));await detectCurrent()}$('analyze').disabled=false;$('analyze').onclick();$('status').textContent='자동 찾기 완료. 희미한 선은 생략하며 그림자·배경이 후보로 표시될 수 있습니다. 손을 선택해 확인하고 수정하세요.'}catch{$('status').textContent='자동 찾기에 실패했습니다. 사진을 다시 선택해 주세요.'}finally{pairStatus()}};
