// Local contrast ridge tracking. Candidate labels rely on an upright, centered palm.
const hands={왼손:null,오른손:null};let currentHand=$('hand').value;
function saveHand(){if(image)hands[currentHand]={image,url,rotation,paths:paths.map(p=>p.map(v=>({...v}))),width:canvas.width,height:canvas.height}}
function showHand(name){saveHand();currentHand=name;$('hand').value=name;const h=hands[name];image=h?.image||null;url=h?.url||null;rotation=h?.rotation||0;paths=h?.paths.map(p=>p.map(v=>({...v})))||[[],[],[],[]];if(h){canvas.width=h.width;canvas.height=h.height;render()}canvas.hidden=!h;$('empty').hidden=!!h;buttons();$('result').hidden=true}
$('hand').onchange=()=>showHand($('hand').value);
function pairStatus(){ $('pair-status').textContent=Object.keys(hands).map(k=>k+' '+(hands[k]?'사진 준비됨':'미입력')).join(' · ');$('auto').disabled=!Object.values(hands).some(Boolean)}
async function loadHand(name,file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024){$('status').textContent='15MB 이하 JPG·PNG·WebP를 선택하세요.';return}const next=URL.createObjectURL(file),im=new Image();try{im.src=next;await im.decode();saveHand();if(hands[name]?.url)URL.revokeObjectURL(hands[name].url);const scale=Math.min(1,1200/Math.max(im.width,im.height));hands[name]={image:im,url:next,rotation:0,paths:[[],[],[],[]],width:Math.round(im.width*scale),height:Math.round(im.height*scale)};image=null;showHand(name);pairStatus();$('status').textContent=name+' 준비 완료. 양손 사진을 선택한 뒤 자동 찾기를 누르세요.'}catch{URL.revokeObjectURL(next);$('status').textContent='사진을 열지 못했습니다.'}}
$('left-file').onchange=()=>loadHand('왼손',$('left-file').files[0]);$('right-file').onchange=()=>loadHand('오른손',$('right-file').files[0]);
function ridgeCandidates(rgba,w,h,hand){const gray=new Float32Array(w*h),ridge=new Float32Array(w*h);for(let i=0;i<gray.length;i++)gray[i]=rgba[i*4]*.299+rgba[i*4+1]*.587+rgba[i*4+2]*.114;for(let y=5;y<h-5;y++)for(let x=5;x<w-5;x++){const i=y*w+x;const contrast=Math.max((gray[i-4]+gray[i+4])/2-gray[i],(gray[i-4*w]+gray[i+4*w])/2-gray[i]);ridge[i]=gray[i]>35&&gray[i]<245?Math.max(0,contrast):0}
// Dynamic paths follow measured contrast, never return a default geometric line.
function track(vertical,lo,hi,start,end){const n=vertical?h:w,m=vertical?w:h,a=Math.floor(n*start),b=Math.floor(n*end),l=Math.floor(m*lo),r=Math.floor(m*hi),span=r-l+1;let prev=new Float32Array(span);const back=[];for(let t=a;t<=b;t++){const next=new Float32Array(span),parents=new Int16Array(span);for(let j=0;j<span;j++){let best=-Infinity,kbest=j;for(let k=Math.max(0,j-2);k<=Math.min(span-1,j+2);k++){const v=prev[k]-Math.abs(j-k)*1.8;if(v>best){best=v;kbest=k}}const x=vertical?l+j:t,y=vertical?t:l+j;next[j]=best+Math.min(25,ridge[y*w+x]);parents[j]=kbest}back.push(parents);prev=next}let j=prev.indexOf(Math.max(...prev)),p=[];for(let t=b;t>=a;t--){p.push({x:(vertical?l+j:t)/w,y:(vertical?t:l+j)/h});j=back[t-a][j]}p.reverse();const strengths=p.map(v=>ridge[Math.min(h-1,Math.floor(v.y*h))*w+Math.min(w-1,Math.floor(v.x*w))]);const supported=strengths.filter(v=>v>5).length/p.length;if(supported<.35||strengths.reduce((a,b)=>a+b,0)/p.length<5)return [];return p.filter((_,i)=>i%3===0||i===p.length-1)}
return [track(true,hand==='왼손'?.42:.22,hand==='왼손'?.78:.58,.42,.82),track(false,.47,.67,.23,.77),track(false,.30,.47,.23,.77),track(true,.42,.62,.55,.86)]}
async function detectCurrent(){paths=[[],[],[],[]];render();const small=document.createElement('canvas');small.width=240;small.height=Math.max(120,Math.round(240*canvas.height/canvas.width));const c=small.getContext('2d');c.drawImage(canvas,0,0,small.width,small.height);paths=ridgeCandidates(c.getImageData(0,0,small.width,small.height).data,small.width,small.height,currentHand);render();buttons();saveHand()}
const oldAnalyze=$('analyze').onclick;
$('analyze').onclick=()=>{saveHand();oldAnalyze();const cards=$('cards');cards.replaceChildren();let lines=[];for(const [name,h] of Object.entries(hands)){if(!h)continue;const title=document.createElement('h3');title.textContent=name+' · 주요 손금 후보';cards.append(title);lines.push(name);h.paths.forEach((p,i)=>{const a=document.createElement('article');a.className='card';const heading=document.createElement('h3');heading.textContent=definitions[i][0];const detail=document.createElement('p');let text='뚜렷한 후보를 찾지 못했습니다. 사진에서 확인하거나 직접 그려 주세요.';if(p.length>1){let len=0;for(let k=1;k<p.length;k++)len+=Math.hypot((p[k].x-p[k-1].x)*h.width,(p[k].y-p[k-1].y)*h.height);const direct=Math.hypot((p.at(-1).x-p[0].x)*h.width,(p.at(-1).y-p[0].y)*h.height);const curved=len/Math.max(1,direct)>1.15;text=detailedReading(i,curved,Math.round(len/Math.hypot(h.width,h.height)*100));}detail.textContent=text;detail.style.whiteSpace='pre-line';a.append(heading,detail);cards.append(a);lines.push(definitions[i][0]+': '+text)})}$('summary').textContent='양손의 주름 후보를 비교하는 재미용 해석입니다. 후보의 이름은 사진 구도에 따른 추정이며, 실제 손금과 일치하는지 확인하세요.';$('copytext').value='손금 노트 · 양손 요약\n'+lines.join('\n\n')+'\n\n건강·수명·성격·미래를 예측하는 과학적 분석이 아닙니다.'};
$('auto').onclick=async()=>{const b=$('auto');b.disabled=true;$('status').textContent='사진의 주름 후보를 찾고 있습니다…';try{saveHand();for(const name of Object.keys(hands)){if(!hands[name])continue;showHand(name);await new Promise(r=>setTimeout(r,20));await detectCurrent()}$('analyze').disabled=false;$('analyze').onclick();$('status').textContent='자동 찾기 완료. 희미한 선은 생략하며 그림자·배경이 후보로 표시될 수 있습니다. 손을 선택해 확인하고 수정하세요.'}catch{$('status').textContent='자동 찾기에 실패했습니다. 사진을 다시 선택해 주세요.'}finally{pairStatus()}};

function detailedReading(i,curved,length){
const shape=curved?'굽음이 있는 선':'비교적 곧은 선';
const descriptions=[
['생명선 · 생활과 활동의 이야기','전통 손금에서 생명선은 엄지 주변을 감싸는 선으로, 생활의 활력과 활동 범위를 상징한다고 이야기합니다.',curved?'넓게 굽은 형태는 다양한 환경을 경험하고 활동 범위를 넓히는 이미지로 풀이합니다. 새로운 장소나 사람을 만나며 일상에 변화를 주는 이야기와 연결합니다.':'비교적 곧게 이어진 형태는 익숙한 환경에서 일정한 생활 리듬을 지키는 이미지로 풀이합니다. 꾸준한 습관과 자신의 속도를 중시하는 이야기와 연결합니다.','생활에 연결해 보기: 새로운 활동과 안정된 루틴 중 요즘 자신에게 필요한 쪽을 생각해 보세요. 실제 체력과 건강은 생활 습관과 의료적 평가로 확인해야 합니다.','선의 길이·진하기로 수명, 질병, 사고 시기를 판단할 수 없습니다.'],
['두뇌선 · 사고방식과 일의 이야기','전통적으로 두뇌선은 생각을 정리하고 문제를 다루는 방식을 상징한다고 이야기합니다.',curved?'굽음이 있는 형태는 상상력과 유연한 관점의 이미지로 풀이합니다. 하나의 정답보다 다양한 가능성을 떠올리는 이야기이며, 창작·기획·새로운 아이디어라는 주제와 연결합니다.':'비교적 곧은 형태는 현실적 판단과 계획의 이미지로 풀이합니다. 순서를 정하고 근거를 확인하며 실행하는 이야기이며, 분석·관리·실무라는 주제와 연결합니다.','일에 연결해 보기: 아이디어를 떠올리는 과정과 계획대로 실행하는 과정 중 어느 쪽에서 편안함을 느끼는지 돌아보세요. 두 방식은 함께 사용할 수 있습니다.','지능, 학력, 실제 업무 능력이나 적합한 직업을 손금으로 판정할 수 없습니다.'],
['감정선 · 감정 표현과 관계의 이야기','전통적으로 손가락 아래를 가로지르는 감정선은 애정과 관계에서의 표현 방식을 상징한다고 이야기합니다.',curved?'굽음이 있는 형태는 감정을 풍부하게 표현하고 관계의 분위기를 살피는 이미지로 풀이합니다. 따뜻한 표현과 공감이라는 주제를 떠올려 볼 수 있습니다.':'비교적 곧은 형태는 감정을 차분하게 정리하고 행동으로 표현하는 이미지로 풀이합니다. 안정적인 소통과 일관된 태도라는 주제를 떠올려 볼 수 있습니다.','관계에 연결해 보기: 마음을 말로 표현하는지, 행동으로 보여 주는지 생각해 보세요. 실제 관계는 서로의 대화와 경험을 바탕으로 이해하는 것이 도움이 됩니다.','연애 성공, 배우자의 성격, 궁합, 결혼 시기, 이별 여부를 예측할 수 없습니다.'],
['운명선 · 직업·사업·재물의 이야기','전통적으로 손목에서 손바닥 위쪽으로 향하는 운명선은 사회 활동과 삶의 방향을 상징한다고 이야기합니다.',curved?'굽음이 있는 형태는 상황에 맞추어 방향을 탐색하는 이미지로 풀이합니다. 여러 역할과 경험을 거치며 자신에게 맞는 길을 찾는 이야기와 연결합니다.':'비교적 곧은 형태는 한 방향에 집중하며 경험을 쌓는 이미지로 풀이합니다. 목표를 정하고 꾸준하게 이어 가는 이야기와 연결합니다.','직업·사업에 연결해 보기: 지금 하는 일에서 쌓고 싶은 경험과 앞으로 시도하고 싶은 역할을 적어 보세요. 재물 이야기는 꾸준한 활동이라는 상징 정도로만 받아들여 주세요.','취업·승진·사업 성공, 재산 규모, 투자 수익이나 연령별 운세를 판단할 수 없습니다.']
];const d=descriptions[i];return '사진에서 측정한 형태\n길이: 사진 대각선 대비 '+length+'% · '+shape+'\n\n전통적 의미\n'+d[1]+'\n\n형태별 풀이\n'+d[2]+'\n\n'+d[3]+'\n\n해석의 범위\n'+d[4]+' 사진의 여백과 검출 경로에 따라 측정값이 달라집니다.'}
