let reportCanvas=null,reportKey='';
const shortMeanings=[['활동 범위를 넓히는 이미지','일정한 생활 리듬의 이미지'],['상상력과 아이디어의 상징','실용적 사고와 계획의 상징'],['관계에서 감정을 풍부하게 표현하는 상징','감정을 간결하게 표현하는 상징'],['방향을 탐색하는 사회 활동의 이미지','한 방향에 집중하는 사회 활동의 이미지']];
function wrapText(c,text,x,y,width,lineHeight){let line='';for(const ch of text){if(c.measureText(line+ch).width>width&&line){c.fillText(line,x,y);y+=lineHeight;line=ch}else line+=ch}if(line)c.fillText(line,x,y);return y+lineHeight}
async function createReport(){await document.fonts.ready;const key=JSON.stringify({paths,hand:$('hand').value,rotation,url});if(reportCanvas&&reportKey===key)return reportCanvas;if(!image||!paths.some(p=>p.length>1))throw new Error('사진과 손금을 먼저 입력해 주세요.');const out=document.createElement('canvas');out.width=1240;out.height=1754;const c=out.getContext('2d');c.fillStyle='#ffffff';c.fillRect(0,0,1240,1754);c.fillStyle='#12243a';c.fillRect(0,0,1240,190);c.fillStyle='#66e0cb';c.font='bold 22px sans-serif';c.fillText('PALM NOTE · 손금 노트',70,62);c.fillStyle='#fff';c.font='bold 46px sans-serif';c.fillText('나의 손금 한 페이지 요약',70,128);c.fillStyle='#546277';c.font='24px sans-serif';const date=new Date().toLocaleDateString('ko-KR');c.fillText(date+' · '+$('hand').value+' · 직접 입력한 선 '+paths.filter(p=>p.length>1).length+'개',70,242);
const scale=Math.min(470/canvas.width,500/canvas.height),w=canvas.width*scale,h=canvas.height*scale;c.fillStyle='#f0f3f8';c.fillRect(70,275,500,520);c.drawImage(canvas,70+(500-w)/2,285+(500-h)/2,w,h);c.fillStyle='#12243a';c.font='bold 30px sans-serif';c.fillText('사진에 표시한 주요 선',630,325);let y=380;definitions.forEach((d,i)=>{c.fillStyle=d[2];c.fillRect(630,y-22,9,30);c.fillStyle='#12243a';c.font='bold 26px sans-serif';c.fillText(d[0],655,y);c.font='22px sans-serif';c.fillStyle='#546277';y=wrapText(c,d[1],655,y+35,490,30)+32});c.font='20px sans-serif';c.fillStyle='#546277';wrapText(c,'색 선은 사용자가 직접 그린 경로입니다. 자동 손금 인식 결과가 아닙니다.',70,832,1100,28);
definitions.forEach((d,i)=>{const top=890+i*155;c.fillStyle='#f2f5f9';c.fillRect(70,top,1100,142);c.fillStyle='#12243a';c.font='bold 27px sans-serif';c.fillText(d[0]+' · '+meanings[i][0],90,top+36);c.font='22px sans-serif';c.fillStyle='#546277';if(paths[i].length<2){c.fillText('미입력 · 보이지 않는 선은 해석하지 않았습니다.',90,top+80);return}const m=measure(paths[i]),curved=m.curve>1.15;c.fillText('사진 대각선 대비 길이 '+Math.round(m.length*100)+'% · '+(curved?'굽음이 있는 선':'비교적 곧은 선'),90,top+71);let reading=shortMeanings[i][curved?0:1];if(i===2)reading='관계와 감정 표현을 상징하는 선';if(i===3)reading='사회 활동과 삶의 방향을 상징하는 선';wrapText(c,'전통적 의미: '+reading+'.',90,top+105,1050,28)});
c.fillStyle='#12243a';c.font='bold 22px sans-serif';c.fillText('재미로 보는 전통적 상징 해석',70,1558);c.fillStyle='#546277';c.font='20px sans-serif';wrapText(c,'손금은 성격·건강·수명·재산·미래를 예측하는 과학적 방법이 아닙니다. 선의 측정값은 사진의 여백과 직접 그리는 방식에 따라 달라집니다.',70,1597,1100,30);c.font='18px sans-serif';c.fillText('사진과 선은 기기 안에서 처리 · 사용자 요청 시에만 파일로 저장',70,1700);reportCanvas=out;reportKey=key;return out}
function downloadBlob(blob,extension){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='palm-note-'+new Date().toISOString().slice(0,10)+'.'+extension;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000)}
function jpegPdf(data,width,height){const binary=atob(data.split(',')[1]),jpeg=Uint8Array.from(binary,ch=>ch.charCodeAt(0)),enc=new TextEncoder(),parts=[],offsets=[0];let size=0;const add=v=>{const b=typeof v==='string'?enc.encode(v):v;parts.push(b);size+=b.length};const object=(n,body)=>{offsets[n]=size;add(n+' 0 obj\n'+body+'\nendobj\n')};add('%PDF-1.4\n');object(1,'<< /Type /Catalog /Pages 2 0 R >>');object(2,'<< /Type /Pages /Kids [3 0 R] /Count 1 >>');object(3,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>');offsets[4]=size;add('4 0 obj\n<< /Type /XObject /Subtype /Image /Width '+width+' /Height '+height+' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '+jpeg.length+' >>\nstream\n');add(jpeg);add('\nendstream\nendobj\n');const stream='q\n595.28 0 0 841.89 0 0 cm\n/Im0 Do\nQ\n';object(5,'<< /Length '+enc.encode(stream).length+' >>\nstream\n'+stream+'endstream');const xref=size;add('xref\n0 6\n0000000000 65535 f \n');for(let i=1;i<=5;i++)add(String(offsets[i]).padStart(10,'0')+' 00000 n \n');add('trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF');return new Blob(parts,{type:'application/pdf'})}
async function exportReport(kind){const button=$(kind);button.disabled=true;try{const report=await createReport();$('report-preview').src=report.toDataURL('image/png');$('report-preview').hidden=false;if(kind==='pdf'){downloadBlob(jpegPdf(report.toDataURL('image/jpeg',.95),report.width,report.height),'pdf')}else if(kind==='png'){const blob=await new Promise(resolve=>report.toBlob(resolve,'image/png'));if(!blob)throw new Error('이미지를 만들지 못했습니다.');downloadBlob(blob,'png')}else{const img=$('print-image');img.src=report.toDataURL('image/png');await img.decode();window.print()}$('export-status').textContent=kind==='print'?'A4 세로 · 배율 100% · 머리글/바닥글 끄기로 인쇄해 주세요.':'한 페이지 요약 파일을 준비했습니다. 다운로드 목록을 확인해 주세요.'}catch(e){$('export-status').textContent=e.message||'저장하지 못했습니다. 다시 시도해 주세요.'}finally{button.disabled=false}}
['pdf','png','print'].forEach(kind=>$(kind).onclick=()=>exportReport(kind));
